#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MOISTURE_SENSOR_PIN 34
#define SUNLIGHT_SENSOR_PIN 35
#define TEMPERATURE_SENSOR_PIN 32

#define RAW_MOISTURE_MIN 0.0
#define RAW_MOISTURE_MAX 1.0

#define RAW_SUNLIGHT_MIN 0.0
#define RAW_SUNLIGHT_MAX 1.0

#define RAW_TEMPERATURE_MIN 0.0
#define RAW_TEMPERATURE_MAX 1.0

#define WIFI_RECONNECT_INTERVAL 10000
#define HYSTERESIS_THRESHOLD 5.0
#define RECOVERY_INTERVAL 5000
#define ALERT_COOLDOWN 1800000

#define LED_COUNT 30
#define LED_PIN 5

#endif